server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
spring.mvc.pathmatch:
  matching-strategy: ant_path_matcher
